# Generated by Django 4.2.3 on 2023-07-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao_kit', models.CharField(max_length=8000, verbose_name='Identificacao do kit')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Codigo de identificacao')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('telhado', models.CharField(choices=[('MINI TRILHO', 'MINI TRILHO'), ('COLONIAL', 'COLONIAL'), ('FIBROMADEIRA', 'FIBROMADEIRA'), ('FIBROMETALICO', 'FIBROMETALICO'), ('ROMANA/AMERICANA', 'ROMANA/AMERICANA'), ('ZINCO/ALUZINCO', 'ZINCO/ALUZINCO'), ('SEM ESTRUTURA', 'SEM ESTRUTURA')], max_length=8000, verbose_name='Tipo de Telhado')),
                ('conexao', models.CharField(max_length=8000, verbose_name='Conexão')),
                ('qnt_modulos', models.IntegerField(verbose_name='Quantidade de Modulos')),
                ('potencia_unitaria', models.IntegerField(verbose_name='Potencia Unitaria Modulo')),
                ('max_overload', models.IntegerField(verbose_name='Overload Maximo')),
                ('kwp', models.FloatField(verbose_name='kWp')),
                ('qnt_inversor1', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de inversor 1')),
                ('invesor1', models.CharField(blank=True, max_length=8000, null=True, verbose_name='inversor 1')),
                ('qnt_inversor2', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de inversor 2')),
                ('invesor2', models.CharField(blank=True, max_length=8000, null=True, verbose_name='inversor 2')),
                ('qnt_cabo_vermelho_m', models.CharField(max_length=8000, verbose_name='Quantidade de Cabo Vermelho Metros')),
                ('mod_cabo_vermelho', models.CharField(blank=True, max_length=8000, null=True, verbose_name='Modelo Do Cabo Vermelho')),
                ('qnt_cabo_preto_m', models.CharField(max_length=8000, verbose_name='Quantidade de Cabo preto (Metros)')),
                ('mod_cabo_preto', models.CharField(blank=True, max_length=8000, null=True, verbose_name='Modelo Do Cabo Preto')),
                ('qnt_pares_conectores', models.IntegerField(verbose_name='Quantidade de Conectores Pares')),
                ('mod_par_conector', models.CharField(max_length=8000, verbose_name='Modelo de Conector par')),
                ('qnt_stringbox', models.IntegerField(verbose_name='Quantidade Stringbox')),
                ('mod_stringbox', models.CharField(max_length=8000, verbose_name='Modelos Stringbox')),
                ('qnt_estrutura1', models.IntegerField(verbose_name='Quantidade de estruturas 1')),
                ('mod_estrutura1', models.CharField(max_length=8000, verbose_name='Modelo Estrutura 1')),
                ('qnt_estrutura2', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de estruturas 2')),
                ('mod_estrutura2', models.CharField(blank=True, max_length=8000, null=True, verbose_name='Modelo Estrutura 2')),
                ('qnt_estrutura3', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de estruturas 3')),
                ('mod_estrutura3', models.CharField(blank=True, max_length=8000, null=True, verbose_name='Modelo Estrutura 3')),
                ('qnt_estrutura4', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de estruturas 4')),
                ('mod_estrutura4', models.CharField(blank=True, max_length=8000, null=True, verbose_name='Modelo Estrutura 4')),
                ('qnt_estrutura5', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de estruturas 5')),
                ('mod_estrutura5', models.CharField(blank=True, max_length=8000, null=True, verbose_name='Modelo Estrutura 5')),
                ('marca_inversor', models.CharField(max_length=8000, verbose_name='Marca do inversor')),
                ('mod_modulo', models.CharField(max_length=8000, verbose_name='Marca do Modulo')),
            ],
            options={
                'verbose_name': 'Kit_data',
                'verbose_name_plural': 'Kits_data',
            },
        ),
    ]
