# Generated by Django 4.2.3 on 2023-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit_data',
            name='codigo',
            field=models.CharField(max_length=8000, unique=True, verbose_name='Codigo de identificacao'),
        ),
    ]
