# Generated by Django 4.2.3 on 2023-07-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0002_alter_kit_data_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit_data',
            name='telhado',
            field=models.CharField(max_length=8000, verbose_name='Tipo de Telhado'),
        ),
    ]
