# Generated by Django 4.2.3 on 2023-07-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0003_alter_kit_data_telhado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=8000, verbose_name='Modelo Cabo')),
                ('qnt_cabo', models.IntegerField(verbose_name='Quant. Cabo(m)')),
                ('cor', models.CharField(blank=True, max_length=250, null=True, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Cabo',
                'verbose_name_plural': 'Cabos',
            },
        ),
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_estrutura1', models.IntegerField(verbose_name='Quantidade de estruturas 1')),
                ('mod_estrutura1', models.CharField(max_length=8000, verbose_name='Modelo Estrutura 1')),
            ],
            options={
                'verbose_name': 'Estrutura',
                'verbose_name_plural': 'Estruturas',
            },
        ),
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_inversor', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de inversor 1')),
                ('marca_inversor', models.CharField(max_length=8000, verbose_name='Marca do inversor')),
            ],
            options={
                'verbose_name': 'Inversor',
                'verbose_name_plural': 'Inversores',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_modulo', models.CharField(max_length=8000, verbose_name='Modelo do Modulo')),
                ('qnt_modulos', models.IntegerField(verbose_name='Quantidade de Modulos')),
                ('marca_modulo', models.CharField(max_length=8000, verbose_name='Marca do Modulo')),
                ('potencia_unitaria', models.IntegerField(verbose_name='Potencia Unitaria Modulo')),
                ('max_overload', models.IntegerField(verbose_name='Overload Maximo')),
                ('kwp', models.FloatField(verbose_name='kWp')),
            ],
            options={
                'verbose_name': 'modulo',
                'verbose_name_plural': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='Pares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_pares_conectores', models.IntegerField(verbose_name='Quantidade de Conectores Pares')),
                ('mod_par_conector', models.CharField(max_length=8000, verbose_name='Modelo de Conector par')),
            ],
            options={
                'verbose_name': 'Pares',
                'verbose_name_plural': 'Paress',
            },
        ),
        migrations.CreateModel(
            name='Stringbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_stringbox', models.IntegerField(verbose_name='Quantidade Stringbox')),
                ('mod_stringbox', models.CharField(max_length=8000, verbose_name='Modelos Stringbox')),
            ],
            options={
                'verbose_name': 'Stringbox',
                'verbose_name_plural': 'Stringboxs',
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao_kit', models.CharField(max_length=8000, verbose_name='Identificacao do kit')),
                ('codigo', models.CharField(max_length=8000, unique=True, verbose_name='Codigo de identificacao')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('telhado', models.CharField(max_length=8000, verbose_name='Tipo de Telhado')),
                ('conexao', models.CharField(max_length=8000, verbose_name='Conexão')),
                ('cabo', models.ManyToManyField(to='excel_processor.cabo', verbose_name='Cabo')),
                ('estrutura', models.ManyToManyField(to='excel_processor.estrutura', verbose_name='Estrutura')),
                ('inversor', models.ManyToManyField(to='excel_processor.inversor', verbose_name='inversor')),
                ('modulos', models.ManyToManyField(to='excel_processor.modulo', verbose_name='Modulo')),
                ('pares', models.ManyToManyField(to='excel_processor.pares', verbose_name='Pares')),
                ('stringbox', models.ManyToManyField(to='excel_processor.stringbox', verbose_name='Stringbox')),
            ],
            options={
                'verbose_name': 'kit',
                'verbose_name_plural': 'kits',
            },
        ),
    ]
