# Generated by Django 4.2.3 on 2023-07-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0004_cabo_estrutura_inversor_modulo_pares_stringbox_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='mod_inversor',
            field=models.CharField(blank=True, max_length=8000, null=True, verbose_name='Modelo do inversor'),
        ),
    ]
