# Generated by Django 4.2.3 on 2023-07-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0007_alter_inversor_mod_inversor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversor',
            name='mod_inversor',
            field=models.CharField(max_length=8000, verbose_name='Modelo do inversor'),
        ),
    ]
